### ISSUE TITLE
Failures since updating to the latest image

### ISSUE THREAD

**Issue by triceam** [cloud-native-toolkit/image-terraform#2]
I'm seeing unexpected failures since we [updated to the latest base image yesterday](https://github.com/cloud-native-toolkit/image-terraform/pull/1)...

```
│ Error: External Program Execution Failed
│ 
│   with module.dev_cluster.data.external.oc_login[0],
│   on .terraform/modules/dev_cluster/main.tf line 17, in data "external" "oc_login":
│   17:   program = ["bash", "${path.module}/scripts/oc-login.sh"]
│ 
│ The data source received an unexpected error while attempting to execute
│ the program.
│ 
│ Program: /bin/bash
│ Error Message: .terraform/modules/dev_cluster/scripts/oc-login.sh: line 40:
│ oc: command not found
│ 
│ State: exit status 1
╵
Error: Process completed with exit code 1.
```

For example:
- https://github.com/cloud-native-toolkit/terraform-k8s-namespace/runs/6193484191?check_suite_focus=true#step:4:173
- https://github.com/cloud-native-toolkit/terraform-tools-argocd/runs/6186695782?check_suite_focus=true
- https://github.com/cloud-native-toolkit/terraform-tools-openshift-cicd/runs/6186829467?check_suite_focus=true#step:4:179

**Comment by triceam** [comment]
As a workaround I've been updating impacted modules from `quay.io/cloudnativetoolkit/terraform:v1.1` to `quay.io/cloudnativetoolkit/cli-tools:v1.1`, which doesn't seem to be having this problem.

**Comment by seansund** [comment]
Many things have changed with the container image since this issue and we aren't seeing it anymore.
